DROP TABLE art_tag;
DROP TABLE art_alias;
DROP TABLE release;
DROP TABLE album;
DROP TABLE artist;

CREATE TABLE artist (
arid    varchar2(50),
arname   varchar2(50),
country varchar2(50),
city varchar2(50),
birthDate varchar2(50),
deathDate varchar2(50),
artype varchar2(30),
gender varchar2(20),
gid varchar2(50),

CONSTRAINT pk_artist PRIMARY KEY (arid),
CONSTRAINT fk_artperson_artgroup FOREIGN KEY (gid) REFERENCES artist(arid)
);

CREATE TABLE art_tag(
arid varchar2(50),
artag varchar2(40),

CONSTRAINT pk_tag PRIMARY KEY (arid,artag),
CONSTRAINT fk_tag_artist FOREIGN KEY (arid) REFERENCES artist(arid)
);

CREATE TABLE art_alias(
arid varchar2(50),
aralias varchar2(40),

CONSTRAINT pk_alias PRIMARY KEY (arid,aralias),
CONSTRAINT fk_alias_artist FOREIGN KEY (arid) REFERENCES artist(arid)
);

CREATE TABLE album(
albid   varchar2(50),
--arid    varchar2(50),
reltype varchar2(20),
title    varchar2(50),
status    varchar2(50),
rellanguage    varchar2(50),
reldate varchar2(50),
format    varchar2(50),
trackCount int,

CONSTRAINT pk_album PRIMARY KEY (albid)
--CONSTRAINT fk_release_artist FOREIGN KEY (arid) REFERENCES artist(arid)
);

CREATE TABLE release (
--relid NUMBER GENERATED by default on null as IDENTITY,
arid varchar2(50),
albid varchar2(50),

CONSTRAINT pk_release PRIMARY KEY (arid, albid),
CONSTRAINT fk_release_artist FOREIGN KEY (arid) REFERENCES artist(arid),
CONSTRAINT fk_release_album FOREIGN KEY (albid) REFERENCES album(albid)
);

--SELECT * FROM ART_ALIAS;
--SELECT * FROM ART_TAG;
--SELECT * FROM release;
--SELECT * FROM album;
--SELECT * FROM artist;

