SELECT * FROM ART_ALIAS;
SELECT * FROM ART_TAG;

SELECT * FROM artist;

DROP TABLE art_alias;
DROP TABLE art_tag;
DROP TABLE artist;
TRUNCATE TABLE ART_ALIAS;
TRUNCATE TABLE ART_TAG;
TRUNCATE TABLE artist;

--DROP TABLE ART_ALIAS;
--DROP TABLE ART_TAG;