DROP TABLE art_tag;
DROP TABLE art_alias;
DROP TABLE release;
DROP TABLE album;
DROP TABLE artist;

CREATE TABLE artist (
arid    varchar2(50),
arname   varchar2(50),
country varchar2(50),
city varchar2(50),
birthDate Date,
deathDate Date,
artype varchar2(20),
gender varchar2(10),
gid varchar2(50),

CONSTRAINT pk_artist PRIMARY KEY (arid),
CONSTRAINT fk_artperson_artgroup FOREIGN KEY (gid) REFERENCES artist(arid)
);

CREATE TABLE art_tag(
arid varchar2(50),
artag varchar2(20),

CONSTRAINT pk_tag PRIMARY KEY (arid,artag),
CONSTRAINT fk_tag_artist FOREIGN KEY (arid) REFERENCES artist(arid)
);

CREATE TABLE art_alias(
arid varchar2(50),
aralias varchar2(20),

CONSTRAINT pk_alias PRIMARY KEY (arid,aralias),
CONSTRAINT fk_alias_artist FOREIGN KEY (arid) REFERENCES artist(arid)
);

CREATE TABLE album(
albid   varchar2(50),
--arid    varchar2(50),
reltype varchar2(20),
title    varchar2(50),
status    varchar2(50),
rellanguage    varchar2(50),
reldate Date,
format    varchar2(50),
trackCount int,

CONSTRAINT pk_album PRIMARY KEY (albid)
--CONSTRAINT fk_release_artist FOREIGN KEY (arid) REFERENCES artist(arid)
);

CREATE TABLE release (
relid NUMBER GENERATED by default on null as IDENTITY,
arid varchar2(50),
albid varchar2(50),

CONSTRAINT pk_release PRIMARY KEY (relid),
CONSTRAINT fk_release_artist FOREIGN KEY (arid) REFERENCES artist(arid),
CONSTRAINT fk_release_album FOREIGN KEY (albid) REFERENCES album(albid)
);

INSERT INTO artist VALUES ('personID','personName', 'us', 'new york', '25-01-1999', '24-02-2000', 'person', 'male', null);
INSERT INTO artist VALUES ('groupID','groupName', 'gr', 'athens', '20-11-2004', '24-02-2008', 'group', null, null);
INSERT INTO artist VALUES ('m1ID', 'm1Name', 'gr', 'athens', null, null, 'member of band', 'female', 'groupID');
INSERT INTO artist VALUES ('m2ID', 'm2Name', 'gr', 'salonika', null, null, 'member of band', 'male', 'groupID');

INSERT INTO album VALUES ('albumID', 'album', 'title1', 'official', 'eng', '09-09-2010', 'CD', 9);
INSERT INTO album VALUES ('compiID', 'compilation', 'title2', 'bootleg', 'turk', '10-10-2009', 'Virl', 10);

INSERT INTO release(arid, albid) VALUES ('groupID', 'albumID');
INSERT INTO release(arid, albid) VALUES ('personID', 'compiID');
INSERT INTO release(arid, albid) VALUES ('groupID', 'compiID');

desc artist;
SELECT * FROM artist WHERE arid='groupID';
SELECT a.arid, b.country, b.arid, b.arname, b.gender FROM artist a JOIN artist b
ON a.arid = b.gid 
WHERE a.arid = 'groupID';--  GROUP BY b.country;


SELECT a.arname , b.reltype, b.albid FROM release r 
JOIN artist a ON a.arid = r.arid
JOIN album b ON b.albid = r.albid
WHERE b.reltype = 'compilation';

--RETURN GROUP MEMBERS
desc artist;
SELECT * FROM artist WHERE arid='groupID';
SELECT a.arid, b.country, b.arid, b.arname, b.gender FROM artist a JOIN artist b
ON a.arid = b.gid 
WHERE a.arid = 'groupID';--  GROUP BY b.country;

select artag from art_tag WHERE arid = 'groupID';
select aralias from art_alias WHERE arid = 'groupID';


